export const APP_NAME = 'Apartment Compliance Hub'
export const APP_TAGLINE = 'Building Standards & Compliance Management'
export const CITY_NAME = 'Metropolis'
export const CONTACT_EMAIL = 'support@compliancehub.fake'
export const CONTACT_PHONE = '555-123-4567'
